### ISSUE TITLE
Question that can be rated

### ISSUE THREAD

**Issue by anastasiamajewski** [anastasiamajewski/capstone_project#1]
### Value statement

As a **person who wants to rate the day**
I need a list of **questions** that can be rated from 1 to 5
so that I can **rate my day**

### Description (Text, Scribble, Wireframe, Design)

- [ ] list of questions
- [ ] questions can be rated by a simple radio button scale from 1 to 5

![IMG_20200430_112109](https://user-images.githubusercontent.com/61710777/80694390-bdc92f80-8ad4-11ea-9bb1-0ac109e08bdb.jpg)

### Acceptance criteria
- [ ] questions have to be shown centered
- [ ] questions are scrolled vertically
- [ ] simple radio button scale has to be from 1 to 5
- [ ] scale has to be placed under the questions

### Tasks

- [x] Create feature branch
- [x] Create (small!) list of questions
- [x] Create radio button scale
- [x] Add some styling

### Size

small
