### ISSUE TITLE
Create new page "calendar" and nav bar

### ISSUE THREAD

**Issue by anastasiamajewski** [anastasiamajewski/capstone_project#10]
## Value statement

As a person who wants to see my days in calendar
I need a calendar function
so that I can see what day it is
##Description (Text, Scribble, Wireframe, Design)

- new page with a calendar

## Acceptance criteria

- [ ] calendar has to be on new page

- [ ] routing has to be implemented

- [ ] calendar should show current day

## Tasks

- [ ] add new page

- [ ] add routing to new page

- [ ] add navbar with link to calendar

- [ ] install react calendar application

- [ ] implement calendar on calendar page

- [ ] styling

## Size

large
