### ISSUE TITLE
Add authentication

### ISSUE THREAD

**Issue by anastasiamajewski** [anastasiamajewski/capstone_project#12]
## Value statement

As a person who enters data in the app
I need a authentication
so that I can be sure, only i can read my entries I made
##Description (Text, Scribble, Wireframe, Design)

- authentication as the first page of the app

## Acceptance criteria

- [ ] authentication has to be the first page of the app

- [ ] app can only be used if the user is signed in

## Tasks

- [ ] add new page

- [ ] add routing to new page

- [ ] add authentication in firebase

- [ ] styling

## Size
medium
