### ISSUE TITLE
Creating entries for ratingresults

### ISSUE THREAD

**Issue by anastasiamajewski** [anastasiamajewski/capstone_project#13]
## Value statement

As a person who wants to have a reflective overview about my day
I need the opportunity to enter my thoughts about the day
so that I can see what exactly was good or bad about my day

## Description (Text, Scribble, Wireframe, Design)

- under the rating result should be a text area where the user can add notes about the day

## Acceptance criteria

- [ ] entries field has to be under the ratingresult
- [ ] entries and rating result should appear on another page
- [ ] new page has to have list full of entries and results of the user

## Tasks

- [ ] add entries field under rating result
- [ ] connect entries and rating
- [ ] add new page
- [ ] add routing to new page
- [ ] show entries and rating on new page
- [ ] styling

## Size

large
