### ISSUE TITLE
Saving rated values in local storage

### ISSUE THREAD

**Issue by anastasiamajewski** [anastasiamajewski/capstone_project#2]
### Value statement

As a person who wants to have an overview about my rated questions
I need my answers to be stored
so that I can see which answers I've chosen

### Description (Text, Scribble, Wireframe, Design)

- [ ]    Radio button answers have to be saved

### Acceptance criteria

- [ ] Radio button answers have do be stored in local storage

### Tasks

- [x] Create feature branch
- [ ] Create component in Storybook
- [ ] Write component tests
- [ ] Add components to app

Size

small
