### ISSUE TITLE
Show average for the rated day

### ISSUE THREAD

**Issue by anastasiamajewski** [anastasiamajewski/capstone_project#9]
## Value statement

As a person who wants to see if my day was good or bad
I need the average value
so that I can see if my day was good or bad

## Description (Text, Scribble, Wireframe, Design)

- ]Average of rating visualized on the ratingresult page

## Acceptance criteria

- [ ] Average has to be calculated

- [ ] Average has to be shown on the ratingresultpage

- [ ] result has to be styled

## Tasks

- [ ] Write a calculation function
- [ ] Create area for average with styling

## Size

small
